# Monitor multiple branches

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "main"
      - "dependencies"
    
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "release/4.3.10"
    labels:
      - "4.3.10"
      - "dependencies"
